In [1]:
import numpy as np

In [2]:
a = np.arange(1,10,dtype='int').reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
a[2,1]

np.int64(8)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a[:,1]

array([2, 5, 8])

In [7]:
a[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [9]:
a = np.arange(1,26,dtype='int').reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [10]:
print(a)
a[1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
print(a)
a[1:3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
print(a)
a[1:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  7,  8,  9, 10]])

In [14]:
print(a)
a[1:4,1:3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [40]:
print(a)
a[1:5,0:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [44]:
print(a)
a[0:5, 0:1]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [45]:
a = np.arange(1,28,dtype='int').reshape(3,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [46]:
a[2,1,1]

np.int64(23)

In [49]:
a[2,2,1]

np.int64(26)

In [50]:
a>10

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [51]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [52]:
x = a[a>10]
print(x)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]


In [56]:
a[a<10] = 111
print(a)

[[[111 111 111]
  [111 111 111]
  [111 111 111]]

 [[ 10 111 111]
  [111 111 111]
  [111 111 111]]

 [[111 111 111]
  [111 111 111]
  [111 111 111]]]


In [57]:
##Random fnction

np.random.random(5)

array([0.21919796, 0.38620982, 0.45262797, 0.607006  , 0.34847492])

In [58]:
np.random.random((3,3))

array([[0.39826462, 0.46649629, 0.8089628 ],
       [0.41800853, 0.78875924, 0.80855957],
       [0.32916044, 0.86627619, 0.65568553]])

In [59]:
x = np.random.randint(45,66,(2,4,3))
print(x)

[[[49 48 56]
  [55 48 48]
  [65 58 56]
  [61 57 60]]

 [[64 60 47]
  [46 47 56]
  [64 61 48]
  [62 54 48]]]


In [60]:
a = np.random.rand(3,3)
print(a)

[[0.00170817 0.34470396 0.92654131]
 [0.37436036 0.10898195 0.68454506]
 [0.88496213 0.01754486 0.27099997]]


In [61]:
a = np.random.randn(3,3)
print(a)

[[ 0.88994233 -0.59762113 -0.00984359]
 [-1.88939508  0.83113468 -0.52969323]
 [ 2.29765249 -1.37298151  1.01369182]]


In [63]:
x = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(x)

np.int64(4)

In [64]:
x = [1,2,3,4,5,6,7,8,9,10]
np.random.permutation(x)

array([ 8,  3,  4,  6, 10,  7,  9,  2,  5,  1])