In [1]:
!pip install numpy

     --------------------------------------- 12.9/12.9 MB 21.1 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\91816\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
one = np.array([1, 2, 3, 4])
print(one)

[1 2 3 4]


In [4]:
two = np.array([[1, 2, 3], [4, 5, 6]])
print(two)

[[1 2 3]
 [4 5 6]]


In [5]:
three = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(three)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [7]:
one.shape

(4,)

In [8]:
two.shape

(2, 3)

In [9]:
three.shape

(1, 3, 3)

In [10]:
one.size

4

In [11]:
two.size

6

In [13]:
three.size

9

In [14]:
three.itemsize

8

In [15]:
three.dtype

dtype('int64')

In [20]:
three3 = three.astype('float')
three3

array([[[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]]])

In [3]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]],dtype="bool")
print(x)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]
