In [1]:
import numpy as np

In [ ]:
# Arange function

a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Linespace Function
## value 
## i = start+ix ((stop - start)/ num-1)

a = np.linspace(1,12,6)
print(a)

[ 1.   3.2  5.4  7.6  9.8 12. ]


In [11]:
## Reshape Function

a = np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [12]:
a.reshape(8,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
## Ravel and Fattlen Function

x = np.arange(1,10).reshape(3,3)
print(x)
x1 = x.ravel()
print(x1)
x[0,0] = 555
print(x)
print(x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[555   2   3]
 [  4   5   6]
 [  7   8   9]]
[555   2   3   4   5   6   7   8   9]


In [ ]:
# Transpose Function

x.T

array([[555,   4,   7],
       [  2,   5,   8],
       [  3,   6,   9]])

In [17]:
a.transpose()

array([[ 1,  9, 17, 25],
       [ 2, 10, 18, 26],
       [ 3, 11, 19, 27],
       [ 4, 12, 20, 28],
       [ 5, 13, 21, 29],
       [ 6, 14, 22, 30],
       [ 7, 15, 23, 31],
       [ 8, 16, 24, 32]])

In [ ]:
## Mathematical Operation

a = np.arange(1,33).reshape(4,8)